#!/usr/bin/env bash

set -e

pip install uv

uv venv --python=3.13 homeassistant

source homeassistant/bin/activate

uv pip install -r requirements.test.txt

hass --config config --script ensure_config

if ! grep -R "logger" config/configuration.yaml >> /dev/null;then
echo "
logger:
  default: error
  logs:
    custom_components.influxdb_query_api: debug

influxdb_query_api:
" >> config/configuration.yaml
fi
